# Generated by Django 5.2.1 on 2025-06-04 12:25

import crr.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCrr', models.CharField(max_length=10, null=True, unique=True, verbose_name='número do crr')),
                ('localFiscalizacao', models.CharField(max_length=100, verbose_name='Local da Fiscalização')),
                ('municipioEstadoFiscalizacao', models.CharField(blank=True, default='São Sebastião - SP', max_length=50, null=True, verbose_name='Município da Fiscalização')),
                ('dataFiscalizacao', models.DateField(verbose_name='Data da fiscalização')),
                ('horaFiscalizacao', models.TimeField(verbose_name='Hora da fiscalização')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('matriculaAgente', models.CharField(max_length=10)),
                ('medidaAdministrativa', models.CharField(blank=True, default='Remoção do veículo ao Depósito', max_length=100, null=True, verbose_name='Medida Administrativa')),
                ('localPatio', models.CharField(blank=True, default='RUA BOLIVIA, Nº202, JARAGUA - SÃO SEBASTIÃO/SP - 11600-748', max_length=100, verbose_name='Pátio')),
                ('placaGuincho', models.CharField(blank=True, max_length=7, verbose_name='Placa do guicho')),
                ('encarregado', models.CharField(blank=True, max_length=50, verbose_name='encarregado do guincho')),
                ('status', models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado'), ('pendente', 'Pendente')], default='pendente', help_text='Status atual do veículo (Retido/Liberado)', max_length=8)),
                ('not_gerada', models.BooleanField(default=False, verbose_name='Status da Notificação')),
                ('edital_emitido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRR',
                'verbose_name_plural': 'CRRs',
            },
        ),
        migrations.CreateModel(
            name='TabelaArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arrendatario', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Nome do arrendatário')),
                ('cnpj_arrendatario', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('endereco_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Endereço')),
                ('numero_arrendatario', models.CharField(blank=True, max_length=6, verbose_name='número')),
                ('complemento_arrendatario', models.CharField(blank=True, max_length=10, verbose_name='Complemento')),
                ('bairro_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Bairro')),
                ('cidade_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Cidade')),
                ('uf_arrendatario', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF')),
                ('cep_arrendatario', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Arrendatário',
                'verbose_name_plural': 'Arrendatários',
            },
        ),
        migrations.CreateModel(
            name='TabelaEnquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('amparo_legal', models.CharField(max_length=100)),
                ('descricao_infracao', models.CharField(max_length=500, verbose_name='Descrição da informação')),
            ],
            options={
                'verbose_name': 'Enquadramento',
                'verbose_name_plural': 'Enquadramentos',
            },
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(blank=True, max_length=11, verbose_name='cnh')),
                ('cnhEstrangeira', models.CharField(blank=True, max_length=11, verbose_name='cnh estrangeira')),
                ('ufCnh', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF da CNH')),
                ('cpfCondutor', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('nomeCondutor', models.CharField(blank=True, max_length=50, verbose_name='Nome do Condutor')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutores', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait', models.CharField(blank=True, max_length=11, verbose_name='Código de AIT')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aits', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=crr.models.upload_path, verbose_name='Imagem (upload via Admin)')),
                ('nomeArquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatarios', to='crr.crr')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crr.tabelaarrendatario', verbose_name='Arrendatário')),
            ],
            options={
                'verbose_name': 'Arrendatário',
                'verbose_name_plural': 'Arrendatários',
            },
        ),
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquadramentos', to='crr.crr')),
                ('enquadramento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crr.tabelaenquadramento', verbose_name='Enquadramento')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=7)),
                ('chassi', models.CharField(blank=True, max_length=20)),
                ('marca', models.CharField(blank=True, max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=20)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('especie', models.CharField(blank=True, choices=[('passageiro', 'Passageiro'), ('carga', 'Carga'), ('misto', 'Misto'), ('tracao', 'Tração'), ('colecao', 'Coleção'), ('especial', 'Especial')], max_length=20, verbose_name='espécie')),
                ('categoria', models.CharField(blank=True, choices=[('oficial', 'Oficial'), ('particular', 'Particular'), ('aluguel', 'Aluguel')], max_length=20)),
                ('ufVeiculo', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF do veículo')),
                ('municipioVeiculo', models.CharField(blank=True, max_length=30, verbose_name='Município do veículo')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='crr.crr')),
            ],
        ),
    ]
