# Generated by Django 4.2.22 on 2026-01-20 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0003_alter_ait_id_alter_arrendatario_id_alter_condutor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Dispositivo')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador Único')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API Key')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Mobile',
                'verbose_name_plural': 'Dispositivos Mobile',
            },
        ),
        migrations.CreateModel(
            name='LoteNumeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.PositiveIntegerField(verbose_name='Número Inicial')),
                ('numero_final', models.PositiveIntegerField(verbose_name='Número Final')),
                ('proximo_numero', models.PositiveIntegerField(verbose_name='Próximo Número')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('esgotado', models.BooleanField(default=False, verbose_name='Esgotado')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='crr.dispositivomobile')),
            ],
            options={
                'verbose_name': 'Lote de Numeração',
                'verbose_name_plural': 'Lotes de Numeração',
                'ordering': ['-criado_em'],
            },
        ),
    ]
