# Generated by Django 4.2.22 on 2026-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0004_dispositivo_mobile_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivomobile',
            name='identificador',
        ),
        migrations.AddField(
            model_name='dispositivomobile',
            name='imei',
            field=models.CharField(blank=True, help_text='Numero IMEI unico do dispositivo (15-17 digitos)', max_length=20, null=True, unique=True, verbose_name='IMEI do Dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivomobile',
            name='matricula_agente',
            field=models.CharField(blank=True, help_text='Matricula do agente responsavel pelo dispositivo', max_length=20, verbose_name='Matricula do Agente'),
        ),
    ]
