# Generated by Django 4.2.22 on 2026-01-31 02:00

import random
from django.db import migrations, models


def gerar_codigos_existentes(apps, schema_editor):
    """Gera codigos de ativacao para dispositivos existentes"""
    Dispositivo = apps.get_model('crr', 'DispositivoMobile')
    codigos_usados = set()
    for disp in Dispositivo.objects.all():
        while True:
            codigo = f"{random.randint(100000, 999999)}"
            if codigo not in codigos_usados:
                codigos_usados.add(codigo)
                disp.codigo_ativacao = codigo
                disp.save(update_fields=['codigo_ativacao'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0005_add_imei_to_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivomobile',
            name='ativado',
            field=models.BooleanField(default=False, help_text='Indica se o dispositivo foi ativado via app mobile', verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='dispositivomobile',
            name='codigo_ativacao',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Codigo de Ativacao'),
        ),
        migrations.RunPython(gerar_codigos_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dispositivomobile',
            name='codigo_ativacao',
            field=models.CharField(blank=True, help_text='Codigo de 6 digitos para ativar o dispositivo no app mobile', max_length=8, unique=True, verbose_name='Codigo de Ativacao'),
        ),
    ]
