# Generated by Django 4.2.22 on 2026-02-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0006_add_codigo_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matricula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Agente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nome'],
            },
        ),
    ]
