# Generated by Django 4.2.22 on 2026-02-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0007_add_agente_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='senha',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Senha (hash)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='senha_alterada',
            field=models.BooleanField(default=False, verbose_name='Senha alterada'),
        ),
    ]
