# Generated by Django 4.2.22 on 2026-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0008_agente_senha_agente_senha_alterada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Assinatura'),
        ),
    ]
