# Generated by Django 4.2.22 on 2026-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0009_add_assinatura_to_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='situacaoEntrega',
            field=models.CharField(blank=True, choices=[('Assinou e recebeu 2a via', 'Assinou e recebeu 2ª via'), ('Recusou assinar e recebeu 2a via', 'Recusou assinar e recebeu 2ª via'), ('Recusou assinar e a receber 2a via', 'Recusou assinar e a receber 2ª via'), ('Condutor ausente', 'Condutor ausente')], default='', max_length=50, verbose_name='Situação de Entrega'),
        ),
    ]
