# Generated by Django 4.2.22 on 2026-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0010_add_situacaoentrega_to_crr'),
    ]

    operations = [
        migrations.AddField(
            model_name='condutor',
            name='assinaturaCondutor',
            field=models.TextField(blank=True, default='', verbose_name='Assinatura do Condutor (base64)'),
        ),
    ]
