# Generated by Django 4.2.22 on 2026-02-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0011_add_assinatura_condutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoteNumeracao',
        ),
    ]
