# Generated by Django 4.2.22 on 2026-02-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0012_remove_lotenumeracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivomobile',
            name='matricula_agente',
        ),
    ]
