# Generated by Django 4.2.22 on 2026-03-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crr', '0013_remove_matricula_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('retido', 'Retido'), ('liberado', 'Liberado'), ('cancelado', 'Cancelado')], default='pendente', help_text='Status atual do veículo (Retido/Liberado)', max_length=10),
        ),
        migrations.CreateModel(
            name='EditalGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número do Edital')),
                ('arquivo', models.FileField(upload_to='editais/', verbose_name='Arquivo DOCX')),
                ('crrs', models.TextField(verbose_name='CRRs Incluídos')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Edital Gerado',
                'verbose_name_plural': 'Editais Gerados',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
