# Generated by Django 4.2.22 on 2026-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0014_add_cancelado_editalgerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivomobile',
            name='matricula_agente',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Matrícula do Agente'),
        ),
    ]
