# Generated by Django 4.2.22 on 2026-03-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0015_readd_matricula_agente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivomobile',
            name='matricula_agente',
        ),
    ]
