# Generated by Django 4.2.22 on 2026-03-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0016_remove_matricula_agente_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='localPatio',
            field=models.CharField(blank=True, default='AV ODISSEU 750 - CANTO DO MAR - SÃO SEBASTIÃO/SP', max_length=100, verbose_name='Pátio'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='situacaoEntrega',
            field=models.CharField(blank=True, choices=[('assinou e recebeu 2a via', 'Assinou e recebeu 2ª via'), ('recusou assinar e recebeu 2a via', 'Recusou assinar e recebeu 2ª via'), ('recusou assinar e a receber 2a via', 'Recusou assinar e a receber 2ª via'), ('condutor ausente', 'Condutor ausente')], default='', max_length=50, verbose_name='Situação de Entrega'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('retido', 'Retido'), ('liberado', 'Liberado'), ('cancelado', 'Cancelado'), ('leiloado', 'Leiloado')], default='pendente', help_text='Status atual do veículo (Retido/Liberado)', max_length=10),
        ),
    ]
