# Generated by Django 5.2.1 on 2025-06-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('data_postagem', models.DateField(verbose_name='Data de postagem')),
                ('numero_controle', models.PositiveIntegerField(unique=True, verbose_name='Numero de controle')),
                ('prazo_leilao', models.DateField(verbose_name='Prazo p/ leilão')),
                ('destinatario', models.CharField(max_length=50, verbose_name='destinatário')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=10, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('cidade_destinatario', models.CharField(max_length=25, verbose_name='Cidade do destinatário')),
                ('uf_destinatario', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF do destinatário')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('crr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='crr.crr', verbose_name='CRR')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
