# Generated by Django 5.2.1 on 2025-06-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_loggeracaoedital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogGeracaoEdital',
        ),
    ]
