# Generated by Django 4.2.22 on 2025-08-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0005_alter_loggeracaoedital_id_alter_notificacao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeracaoedital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='numeroedital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
